import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my compilation of<br />
          Stephen Grider's <a href="https://www.udemy.com/course/react-redux/">React/Redux course!</a>
        </h1>

        <p className={styles.description}>
          Here are some apps created from the course:
        </p>

        <div className={styles.grid}>
          <a
            href="https://pics-eight-beta.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Image list &rarr;</h2>
            <p>From a search bar, make API requests to get images and display them in a grid</p>
          </a>

          <a
            href="https://seasons-sable.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Seasons &rarr;</h2>
            <p>Prompt for geolocation and display the season respectively</p>
          </a>

          <a
            href="https://videos-hooks-nu-indol.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Videos &rarr;</h2>
            <p>Using hooks, request videos from YouTube API and display in a list</p>
          </a>

          <a
            href="https://streams-scoutan.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}>
            <h2>Streams &rarr;</h2>
            <p>Using Redux, Google OAuth 2.0 login, manage a JSON database via REST API</p>
          </a>

          <h3 className={styles.subtitle}>
            Also, check out my first personal React project!
          </h3>

          <a
            href="https://chuko-cra.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Chuko &rarr;</h2>
            <p>Web scraping using React! <br /> (Create-React-App ver.)</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
